POST http://localhost:8080/
Content-Type: text/plain

https://practicum.yandex.ru/




GET http://localhost:8080/c4MKtx
GET http://localhost:8080/asd/as

GET http://localhost:8080/bwVq7Z

curl -v  -X POST localhost:8080 -H 'content-type: plain/text'  --data  "https://practicum.yandex.ru/" 

curl -v -X GET http://localhost:8080/eCxA1M
curl -v -X GET http://localhost:8080/cgdU2E


POST http://localhost:8080/api/shorten
Content-Type: application/json
Accept-Encoding: gzip
{
    "url":"https://practicum.yandex.ru/"
}

POST http://localhost:8080/
Content-Type: application/json
{
    "url":"https://practicum.yandex.ru/"
}

POST http://localhost:8080/api/shorten
Accept-Encoding: deflate
Content-Type: application/json
{
    "url":"https://practicum.yandex.ru/"
}


POST http://localhost:8080/
Content-Type: text/plain

http://hphqha71djxtv.net/cktnspsq4jfvqs


POST http://localhost:8080/
Content-Type: text/plain
Content-Encoding: gzip


POST http://localhost:8080/api/shorten
Accept-Encoding: gzip
Content-Encoding: gzip
Content-Type: application/json
{
    "url":"https://practicum.yandex.ru/"
}


POST http://localhost:8080/
Content-Type: text/plain

http://hphqha71djxtv.net/



# host=localhost port=5432 user=postgres password=postgres dbname=shortener sslmode=disable

GET http://localhost:8080/ping


go run cmd/shortener/main.go -a localhost:8080 -b http://localhost:8080 -d "host=localhost port=5432 user=postgres password=postgres dbname=shortener sslmode=disable"

goose -dir migrations postgres "postgresql://postgres:postgres@localhost:5432/shortener?sslmode=disable" up