POST http://localhost:8080/
Content-Type: text/plain

https://practicum.yandex.ru/




GET http://localhost:8080/QMxHy
GET http://localhost:8080/asd/as

GET http://localhost:8080/bwVq7Z

curl -v  -X POST localhost:8080 -H 'content-type: plain/text'  --data  "https://practicum.yandex.ru/" 

curl -v -X GET http://localhost:8080/eCxA1M