POST http://localhost:8081/
Content-Type: text/plain
https://practicum.yandex.ru/

GET http://localhost:8080/QMxHy
GET http://localhost:8080/asd/as

curl -X POST localhost:8080 -H 'content-type: plain/text'  --data  "https://practicum.yandex.ru/" 
