// Code generated by go generate; DO NOT EDIT.
// This file was generated by reset.go

package model

func (rs *AuditMessage) Reset() {
	if rs == nil {
		return
	}
	rs.TS = 0
	rs.Action = ""
	rs.UserID = ""
	rs.URL = ""
}
