package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"github.com/grizlaz/ya-shortener/internal/logger"
	"go.uber.org/zap"
)

type PackageInfo struct {
	Name       string
	Structures []StructInfo
}

type StructInfo struct {
	Name   string
	Fields []*ast.Field
}

func main() {
	err := GenerateResetFiles(".")
	if err != nil {
		logger.Log.Fatal("error generate reset files", zap.Error(err))
	}
}

func GenerateResetFiles(rootDir string) error {
	pkgs, err := findStructsWithResetComment(rootDir)
	if err != nil {
		return err
	}

	for pkgPath, pkgInfo := range pkgs {
		if len(pkgInfo.Structures) == 0 {
			continue
		}
		filePath := filepath.Join(pkgPath, "reset.gen.go")
		content, err := format.Source(generateFileContent(pkgInfo))
		if err != nil {
			return fmt.Errorf("failed to format %s: %w", filePath, err)
		}
		if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
			return err
		}
	}
	return nil
}

func findStructsWithResetComment(rootDir string) (map[string]*PackageInfo, error) {
	result := make(map[string]*PackageInfo)

	err := filepath.WalkDir(rootDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil
		}

		relPath, err := filepath.Rel(rootDir, filepath.Dir(path))
		if err != nil {
			relPath = filepath.Dir(path)
		}

		pkgInfo, ok := result[relPath]
		if !ok {
			pkgInfo = &PackageInfo{Name: file.Name.Name}
			result[relPath] = pkgInfo
		}

		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			hasResetGlobal := hasResetComment(genDecl.Doc)

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				if hasResetGlobal || hasResetComment(typeSpec.Doc) {
					fields := structType.Fields.List
					pkgInfo.Structures = append(pkgInfo.Structures, StructInfo{
						Name:   typeSpec.Name.Name,
						Fields: fields,
					})
				}
			}
		}
		return nil
	})

	return result, err
}

func hasResetComment(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, comment := range doc.List {
		text := strings.TrimSpace(comment.Text)
		if strings.HasPrefix(text, "//") {
			text = strings.TrimPrefix(text, "//")
		} else if strings.HasPrefix(text, "/*") {
			text = strings.TrimPrefix(text, "/*")
			text = strings.TrimSuffix(text, "*/")
		}
		text = strings.TrimSpace(text)
		if text == "generate:reset" {
			return true
		}
	}
	return false
}

func generateFileContent(pkgInfo *PackageInfo) []byte {
	var sb bytes.Buffer
	sb.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	sb.WriteString("// This file was generated by reset.go\n\n")
	sb.WriteString("package ")
	sb.WriteString(pkgInfo.Name)
	sb.WriteString("\n\n")

	for _, st := range pkgInfo.Structures {
		sb.WriteString(generateMethod(st))
		sb.WriteString("\n")
	}
	return sb.Bytes()
}

func generateMethod(st StructInfo) string {
	var sb strings.Builder
	sb.WriteString("func (rs *")
	sb.WriteString(st.Name)
	sb.WriteString(") Reset() {\n")
	sb.WriteString("\tif rs == nil {\n\t\treturn\n\t}\n")

	for _, field := range st.Fields {
		var accessor string
		if len(field.Names) > 0 {
			accessor = "rs." + field.Names[0].Name
		} else {
			switch t := field.Type.(type) {
			case *ast.Ident:
				accessor = "rs." + t.Name
			case *ast.SelectorExpr:
				accessor = "rs." + t.Sel.Name
			default:
				continue
			}
		}

		code := generateResetCode(accessor, field.Type)
		if code != "" {
			sb.WriteString("\t")
			sb.WriteString(code)
			sb.WriteString("\n")
		}
	}

	sb.WriteString("}\n")
	return sb.String()
}

func generateResetCode(accessor string, typ ast.Expr) string {
	switch t := typ.(type) {
	case *ast.StarExpr:
		elem := t.X
		if isBasicType(elem) {
			return "if " + accessor + " != nil { *" + accessor + " = " + basicZero(elem) + " }"
		}
		if isSliceType(elem) {
			return "if " + accessor + " != nil { *" + accessor + " = (*" + accessor + ")[:0] }"
		}
		if isMapType(elem) {
			return "if " + accessor + " != nil { clear(*" + accessor + ") }"
		}
		return "if " + accessor + " != nil { if v, ok := " + accessor + ".(interface{ Reset() }); ok { v.Reset() } }"

	case *ast.Ident:
		if isBasicType(t) {
			return accessor + " = " + basicZero(t)
		}
		return "if v, ok := " + accessor + ".(interface{ Reset() }); ok { v.Reset() }"

	case *ast.ArrayType:
		if t.Len == nil {
			return accessor + " = " + accessor + "[:0]"
		}
		return ""

	case *ast.MapType:
		return "clear(" + accessor + ")"

	case *ast.SelectorExpr:
		return "if v, ok := " + accessor + ".(interface{ Reset() }); ok { v.Reset() }"

	case *ast.StructType:
		return "if v, ok := " + accessor + ".(interface{ Reset() }); ok { v.Reset() }"

	default:
		return ""
	}
}

func isBasicType(expr ast.Expr) bool {
	ident, ok := expr.(*ast.Ident)
	if !ok {
		return false
	}
	switch ident.Name {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64",
		"complex64", "complex128",
		"string", "bool", "byte", "rune":
		return true
	}
	return false
}

func isSliceType(expr ast.Expr) bool {
	arr, ok := expr.(*ast.ArrayType)
	return ok && arr.Len == nil
}

func isMapType(expr ast.Expr) bool {
	_, ok := expr.(*ast.MapType)
	return ok
}

func basicZero(expr ast.Expr) string {
	ident, ok := expr.(*ast.Ident)
	if !ok {
		return "nil"
	}
	switch ident.Name {
	case "string":
		return `""`
	case "bool":
		return "false"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"byte", "rune":
		return "0"
	case "float32", "float64":
		return "0.0"
	case "complex64", "complex128":
		return "0+0i"
	default:
		return "nil"
	}
}
