// Code generated by go generate; DO NOT EDIT.
// This file was generated by reset.go

package audit

func (rs *Audit) Reset() {
	if rs == nil {
		return
	}
	clear(rs.observers)
}

func (rs *Observer) Reset() {
	if rs == nil {
		return
	}
	rs.id = ""
	if v, ok := rs.storage.(interface{ Reset() }); ok {
		v.Reset()
	}
}
